#==========================================================
#= Articoli Web Service - Autenticazione OAUTH2 keycloak
#==========================================================
server:
  port: 5051
  
spring:
  application:
    name: ArticoliWebService
  banner:
    image:
      location: classpath:banner.txt
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: 123_Stella
    url: jdbc:postgresql://localhost:5433/Alphashop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ==============================================================
# = Propriet√† Livello Log
# = Default ERROR, WARN e INFO 
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ============================================================== 
logging:
  file:
    name: './logs/ArtSrv.log' #file inserito nella cartella logs 
    max-size: 1MB
    #path: "/logs"
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n"
    #console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    
  # Livello del Log generale (default INFO)
  level:
   root: INFO
  # Livello di log specifico
   org.springframework.security: DEBUG
   org.hibernate: INFO
   org.springframework.web: INFO
   com.staipa.webapp.controller: INFO
    
# ==============================================================
# = Parametri Sicurezza OAUTH2 con KeyCloack 
# ==============================================================
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: Alphashop
  resource: ArticoliWebService
  public-client: true 
  
  
  